# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39f3f8c63b030e75920bef54114b807abf1a57be75dd3c0860d3557affab4558c7b9ba613bb8b5d81858e5e78814042da9d8178514983b35f1815f6934700f1f

test:
  secret_key_base: 2a86de0249284627d874c38a001018348514c836edd447623c1ef3f50f92b4210e829aa79dde5cdb64fc601063517e1bb806965b7176d5c5ffd11db4c4925a63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
